authentication/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'auth'
urlpatterns = [
    path('register/', views.register_page, name="reg"),
    path('login/', views.login_page, name='login'),
    path('reset_password/', view=auth_views.PasswordResetView.as_view(template_name='authentication/password_reset.html'), name='reset_password'),
    path('logout/', views.logout_page, name='logout'),
    path('users/', views.UsersView.as_view(), name='users'),
    path('profile<int:pk>/', views.profile_page, name='profile'),
    path('profile<int:pk>/authentication/customer', views.customers_page, name='customers'),
]

polls/urls.py
from django.urls import path
from . import views
#limit class views
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy

app_name = 'polls'
urlpatterns = [
    path('', view=views.IndexView.as_view(), name='index'),
    path('polls/new/', view=login_required(views.create_urls), name='new'),#views.create_urls
    path('polls/update/<int:pk>/', view=views.update_urlentry, name="update"),
    path('polls/delete/<int:pk>/', view=login_required(views.DeleteUrlentry.as_view(), login_url=reverse_lazy('auth:login')), name='delete'),
    path('details/<int:pk>/', view=login_required(views.DetailView.as_view(), login_url=reverse_lazy('auth:login')), name='detail'),
    path('polls/<int:pk>/results/', view=login_required(views.ResultsView.as_view(), login_url=reverse_lazy('auth:login')), name='results'),
    path('polls/<int:pk>/results/get', view=views.ClicksView.as_view(), name='get'),
    path('<str:hash>/', view=views.add_lead_and_redirect, name='short'),
]

urls/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
# from .views import *
#from . import views
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
# from polls import *
# from polls.views import *


from django.conf.urls import include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
    path('reset/<uidb64>/<token>/', view=auth_views.PasswordResetConfirmView.as_view(template_name='authentication/reset_password_done.html'), name='password_reset_confirm'),
    path('reset_password_sent/', view=auth_views.PasswordResetDoneView.as_view(template_name='authentication/reset_password_sent.html'), name='password_reset_done'),
    path('reset_password_complete/', view=auth_views.PasswordResetCompleteView.as_view(template_name='authentication/reset_password_complete.html'), name='password_reset_complete'),
    path('auth/', include('authentication.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

authentication/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# from django.contrib.auth.models import Group

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    def get_absolute_url(self):
        return reverse('auth:profile', args=(self.pk,))
    # def is_my_customer(self):
    #     group = Group.objects.filter(id=profile.user.id).all()
    #     for grp in group:
    #         if str(grp).find('customer') >= 0:
    #             groupstring = True
    #         else:
    #             groupstring = False
    #     return True

class Custcode(models.Model):  #data that gives access to customer functions
    codeword = models.CharField(max_length=16)

authentication/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class CheckCustomerForm(forms.Form):  #form for granting access to customer functions
        codeword = forms.CharField(max_length=16, label='codeword')

authentication/views.py
from django.shortcuts import render, redirect
from .forms import CreateUserForm, CheckCustomerForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .decorators import unauthenticated_user, allowed_users, staff_only
from django.contrib.auth.models import User, Group
from django.views import generic
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group, User
from .models import Profile, Custcode
import json
import os

#import secrets from secrets.json file
def get_secret(setting):
    with open('secrets.json') as secrets_file:
        secrets = json.load(secrets_file)
    """Get secret setting or fail with ImproperlyConfigured"""
    try:
        return secrets[setting]
    except:
        pass


@login_required(login_url='auth:login')
# @allowed_users(allowed_roles=['customer', 'admin'])
def profile_page(request, pk):  #shows profile details
    profile = Profile.objects.get(pk=pk)
    group = Group.objects.filter(id=profile.user.id).all()
    groupstring = 'User'
    if profile.user.is_staff:
        groupstring = 'Customer'
    return render(request, 'authentication/profile.html', context={
        'profile': Profile.objects.get(pk=pk),
        'group':group,
        'groupstring':groupstring,
    })

decorators = [login_required(login_url='auth:login'), staff_only]
@method_decorator(staff_only, name='dispatch')
class UsersView(generic.ListView):  #this page is available only to admin and serves to see all users and manipulate their rights
    template_name = 'authentication/users.html'
    context_object_name = 'user_list'
    def get_queryset(self):
        return Profile.objects.all()

@login_required(login_url='auth:login')
def customers_page(request, pk): #this page is for granting access to is_staff variable
    groupstring = 'user'
    profile = Profile.objects.get(pk=pk)
    user = profile.user
    if request.method == "POST":
        if not request.user.is_superuser:
            form = CheckCustomerForm(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                if cd['codeword']==get_secret('SECRET_KEY'):
                    if user.is_staff==False:
                        user.is_staff=True
                    user.save()
                #Profile.objects.create(user=user).save()
                    messages.success(request, 'User was successfully addedd to Customers group')
                else:
                    messages.error(request, 'Incorrect codeword, please try again')
        else:
            profile.user.is_staff = not user.is_staff
            profile.user.save()
    else:
        if request.user.is_superuser:
            user = User.objects.get(pk=pk)
            user.is_staff = not user.is_staff
            groupstring = 'user'
            user.save()
        form = CheckCustomerForm()
        if form.is_valid():
            form.save()
    group = user.groups.all()  ### other places
    for grp in group:
        if str(grp).find('customer')>=0:
            groupstring = 'customer'
        else:
            groupstring = 'user'
    return render(request, 'authentication/customer.html', context={
        'profile': Profile.objects.get(pk=pk), 'group': group, 'method': request.method,
        'form': form,
        })


@unauthenticated_user
def register_page(request):
    # if not Group.objects.filter(name='customer').exists():
    #     Group.objects.create(name='customer')
    #     Group.objects.create(name='admin')
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            messages.success(request, 'Account was created for ' + form.cleaned_data.get('username'))
            return redirect('auth:login')
        else:
            messages.error(request, 'Got a registration error: ' + str(form.error_messages))
    else:
        form = CreateUserForm()
    context = {'form': form}
    return render(request, 'authentication/reg.html', context)

@unauthenticated_user
def login_page(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('polls:index')
        else:
            messages.warning(request, 'Username or Password is incorrect')
    return render(request, 'authentication/login.html')

def logout_page(request):
    logout(request)
    return redirect('auth:login')

authentication/templates/authentication/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block Title %}Authentication{% endblock %}</title>
    <style type="text/css">

    </style>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" />
</head>
<body>
    {% include 'authentication/nav.html' %}
    <div class="container">
        {% block Body %}{% endblock %}
    </div>
    <script src="{% static 'js/bootstrap.bundle.js' %}" type="text/javascript"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</body>
</html>

authentication/templates/authentication/customer.html
{% extends 'polls/base.html' %}
{% block Title %}Customer registration{% endblock %}
{% block Body %}
    <br>
    <strong>User Name:</strong>{{ profile.user.username }}
    <br>
    <!-- statistics -->
    <strong>Customer: </strong>{{ profile.user.is_staff }}
    <br>
{% if not request.user.is_staff %}
     <br>
    <form action="" method="post">
        <fieldset>
            <legend>Upgrade your profile to Customer</legend>
            {% csrf_token %}
            {% if form.errors %}
                <p style="color: orangered">Got errors! {{ form.errors }}</p>
            {% endif %}
            {% for message in messages %}
                <p style="color: turquoise">{{ message }}</p>
            {% endfor %}
            <p>{{ form.codeword.label }} {{ form.codeword }} </p>
            <input type="submit" class="btn btn-warning" value="Check codeword">
        </fieldset>
    </form>
{% endif %}

{% if request.user.is_superuser %}
<a class="btn btn-warning" onclick="location.href='{% url 'auth:profile' profile.user.id %}'" role="button">Go back</a>
{% endif %}

{% endblock %}

authentication/templates/authentication/login.html
{%  extends 'authentication/base.html' %}
{% block Title %}Log-in{% endblock %}
{% block Body %}
    <form method="post" action="">
        <fieldset>
            <legend>Login</legend>
            {% csrf_token %}
            {% for message in messages %}
                <p style="color: turquoise">{{ message }}</p>
            {% endfor %}
            <label for="username">Username</label>
            <input type="text" name="username" id="username">
            <br>
            <label for="password">Password</label>
            <input type="password" name="password" id="password">
            <input type="submit" class="btn btn-danger" value="LogIn">
        </fieldset>
    </form>
{% endblock %}

authentication/templates/authentication/nav.html
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #34ebd2;">
  <div class="container container-fluid">
<img src="https://u9.by/uby/U9logob.png" width="222" height="80"></img>
          <a class="navbar-brand" href="#"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
          <a class="nav-link" href="{% url 'polls:index' %}" aria-current="page">Home</a>
        </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'auth:login' %}">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%  url 'auth:reset_password' %}">Forgot Password</a>
      </li>
              <li class="nav-item">
        <a class="nav-link" href="{% url 'auth:reg' %}">Register</a>
      </li>
    </ul>
  </div>
</div>
<div class="container">
      <input type="button" class="btn btn-info" onclick="location.href='https://a.u9.by'" value="Freeware soft & music">
      </div>
</nav>

authentication/templates/authentication/password_reset.html
{%  extends 'authentication/base.html' %}
{% block Title %}Password Reset{% endblock %}
{% block Body %}
    <form method="post">
        <fieldset>
            <legend>Password Reset</legend>
            <span>Enter your email address and we'll send you a link to reset your password.</span>
            <br>
            {% csrf_token %}
            {% for message in messages %}
                <p style="color: turquoise">{{ message }}</p>
            {% endfor %}
            <label for="email">Email</label>
            <input type="email" name="email" id="email">
        </fieldset>
        <br>
            <input type="submit" class="btn btn-warning" value="Reset my Password">
    </form>
{% endblock %}

authentication/templates/authentication/profile.html
{% extends 'polls/base.html' %}
{% block Title %}User Profile{% endblock %}
{% block Body %}
    <strong>User Name:</strong>{{ profile.user.username }}
    <br>
    <strong>User Email:</strong>{{ profile.user.email }}
    <br>
    <!-- statistics -->
    <strong>Customer: </strong>{{ profile.user.is_staff }}
    <br>
    {% if request.user.is_superuser %}
    <strong>Superuser: </strong>{{ profile.user.is_superuser }}
    <br>
    {% endif %}

    {% if not profile.user.is_staff and not request.user.is_superuser %}
    <a class="btn btn-warning" href="authentication/customer" role="button">Upgrade to our Customer</a>
    {% endif %}
    {% if request.user.is_superuser and not profile.user.is_staff %}
    <a class="btn btn-danger" href="authentication/customer" role="button">Add Customer privileges</a>
    {% endif %}
    {% if request.user.is_superuser and profile.user.is_staff %}
    <a class="btn btn-danger" href="authentication/customer" role="button">Remove Customer privileges</a>
    {% endif %}
{% endblock %}

authentication/templates/authentication/reg.html
{%  extends 'authentication/base.html' %}
{% block Title %}Registration{% endblock %}
{% block Body %}
    <form method="post" action="">
        <fieldset>
            <legend>Register</legend>
            {% csrf_token %}
            {% if form.errors %}
                <p style="color: orangered">Got errors! {{ form.errors }}</p>
            {% endif %}
            {% for message in messages %}
                <p style="color: turquoise">{{ message }}</p>
            {% endfor %}
            <div class="form-group row">
                 <label for="inputPassword" class="col-sm-2 col-form-label">{{ form.username.label }}</label>
                 <div class="col-sm-10">
            <p> {{ form.username }} </p></div>
            </div>
            <div class="form-group row">
                 <label for="inputPassword" class="col-sm-2 col-form-label">{{ form.email.label }}</label>
                 <div class="col-sm-10">
            <p> {{ form.email }} </p></div>
            </div>
            <div class="form-group row">
                 <label for="inputPassword" class="col-sm-2 col-form-label">{{ form.password1.label }}</label>
                 <div class="col-sm-10">
            <p> {{ form.password1 }} </p></div>
            </div>
            <div class="form-group row">
                 <label for="inputPassword" class="col-sm-2 col-form-label">{{ form.password2.label }}</label>
                 <div class="col-sm-10">
            <p> {{ form.password2 }} </p></div>
            </div>
           <div class="form-group row">
               <div class="col-sm-3"></div>
               <div class="col-sm-4">
            <input type="submit" class="btn btn-warning" value="Register">
            </div>
            </div>
        </fieldset>
    </form>
{% endblock %}

authentication/templates/authentication/reset_password_complete.html
{%  extends 'authentication/base.html' %}
{% block Title %}Password Reset{% endblock %}
{% block Body %}
    <div class="content h-auto" style="margin-top: auto">
        <div class="container-fluid h-auto">
            <div class="row h-auto">
                <div class="col-md-8 col-md-offset-2" style="margin: auto;">
                    <div class="card">
                        <div class="header text-center">
                            <h4 class="title">Password Reset Complete</h4>
                            <p class="category">
                                Your password has been reset.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

authentication/templates/authentication/reset_password_done.html
{%  extends 'authentication/base.html' %}
{% block Title %}Password Reset Done{% endblock %}
{% block Body %}
    <form method="post" class="container">
        <fieldset>
            <legend>Enter new password</legend>
            <span>Please enter your new password twice so we can verify you typed it in correctly.</span>
            <br>
            {% csrf_token %}
            {% for message in messages %}
                <p style="color: turquoise">{{ message }}</p>
            {% endfor %}
            <fieldset class="module aligned">
                <input class="hidden" autocomplete="username" value="rand4" hidden>
                <div class="form-row field-password1">
                    <label for="id_new_password1">New password:</label>
                    <input type="password" name="new_password1" autocomplete="new-password" required="" id="id_new_password1">
                </div>
                <div class="form-row field-password2">
                    <label for="id_new_password2">Confirm password:</label>
                    <input type="password" name="new_password2" autocomplete="new-password" required="" id="id_new_password2">
                </div>
                <input type="submit" class="btn btn-primary" value="Change my password">
            </fieldset>
        </fieldset>
    </form>
{% endblock %}

authentication/templates/authentication/reset_password_sent.html
{%  extends 'authentication/base.html' %}
{% block Title %}Password Reset{% endblock %}
{% block Body %}
    <div class="content h-auto" style="margin-top: auto">
        <div class="container-fluid h-auto">
            <div class="row h-auto">
                <div class="col-md-8 col-md-offset-2" style="margin: auto;">
                    <div class="card">
                        <div class="header text-center">
                            <h4 class="title">Password Reset Sent</h4>
                            <p class="category">
                                We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.
                            </p>
                            <p class="category">
                                If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

authentication/templates/authentication/users.html
{% extends 'polls/base.html' %}
{% block Title %}Users{% endblock %}
{% block Body %}
<style>
   .colortext {
     color: red; /* Красный цвет выделения */
   }
  </style>
{% if user_list %}
<table class="table table-hover">
  <thead class="thead-light">
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Operations</th>
    </tr>
  </thead>
            {% for profile in user_list %}
    <tr>
              <th><b>{{ profile.user.username }}</b>   {% if profile.user.is_staff %} <span class="colortext">(customer)</span>  {% endif %}</th>
        <th>{{ profile.user.email }}</th>
            <th><button type="button" class="btn btn-warning" onclick="location.href='{{ profile.get_absolute_url }}'">Open</button> </th>
        </tr>
            {% endfor %}

</table>
    {% endif %}
{% endblock %}