authentication/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'auth'
urlpatterns = [
    path('register/', views.register_page, name="reg"),
    path('login/', views.login_page, name='login'),
    path('reset_password/', view=auth_views.PasswordResetView.as_view(template_name='authentication/password_reset.html'), name='reset_password'),
    path('logout/', views.logout_page, name='logout'),
    path('users/', views.UsersView.as_view(), name='users'),
    path('profile<int:pk>/', views.profile_page, name='profile'),
    path('profile<int:pk>/authentication/customer', views.customers_page, name='customers'),
]

polls/urls.py
from django.urls import path
from . import views
#limit class views
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy

app_name = 'polls'
urlpatterns = [
    path('', view=views.IndexView.as_view(), name='index'),
    path('polls/new/', view=login_required(views.create_urls), name='new'),#views.create_urls
    path('polls/update/<int:pk>/', view=views.update_urlentry, name="update"),
    path('polls/delete/<int:pk>/', view=login_required(views.DeleteUrlentry.as_view(), login_url=reverse_lazy('auth:login')), name='delete'),
    path('details/<int:pk>/', view=login_required(views.DetailView.as_view(), login_url=reverse_lazy('auth:login')), name='detail'),
    path('polls/<int:pk>/results/', view=login_required(views.ResultsView.as_view(), login_url=reverse_lazy('auth:login')), name='results'),
    path('polls/<int:pk>/results/get', view=views.ClicksView.as_view(), name='get'),
    path('<str:hash>/', view=views.add_lead_and_redirect, name='short'),
]

urls/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
# from .views import *
#from . import views
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
# from polls import *
# from polls.views import *


from django.conf.urls import include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
    path('reset/<uidb64>/<token>/', view=auth_views.PasswordResetConfirmView.as_view(template_name='authentication/reset_password_done.html'), name='password_reset_confirm'),
    path('reset_password_sent/', view=auth_views.PasswordResetDoneView.as_view(template_name='authentication/reset_password_sent.html'), name='password_reset_done'),
    path('reset_password_complete/', view=auth_views.PasswordResetCompleteView.as_view(template_name='authentication/reset_password_complete.html'), name='password_reset_complete'),
    path('auth/', include('authentication.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

polls/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
import math
enc_str = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ23456789"
#print(len(enc_str))
reserved = len(enc_str) ** 3  # 3-symbols address space - from 0 to 12 960 000 - is reserved for registered users only.
max_capacity = len(enc_str) ** 5  # maximal address - 5 symbols
#in 4 symbols we can save 12960000 days or 35506.849315068495 years
#in 5 symbols we can save 777600000 links daily
#unregistered users address space from  12960000 to 777600000


# Create your models here.
class Urlentry(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    create_date = models.DateTimeField('date created', auto_now=True)
    url_text = models.TextField()
    url_id = models.BigIntegerField()
    url_short = models.CharField(max_length=7)
    snapshot = models.TextField()
    qr_code = models.TextField()
    datetime_available_from = models.DateTimeField('url available from', auto_now=False)
    datetime_available_to = models.DateTimeField('url available to', auto_now=False)
    partner_ads = models.TextField()
    def __str__(self):
        return self.url_short
    def num_to_sym_unregistered(intnum2):
        # converts numbers to 4-5-symbols string
        # only registered users can create shortened links with 4 symbols like u9.by/aBcD others - only 5 symbols length
        # intnum=intnum+reserved
        out_str = ''
        intnum=intnum2+reserved
        if (intnum > reserved) and (intnum < max_capacity):
            while intnum > len(enc_str) - 1:
                current = intnum % (len(enc_str) - 1)
                # print ('division=',current,enc_str[current])
                out_str = out_str + enc_str[current]
                intnum = math.floor(intnum / (len(enc_str) - 1))
                # print('rest=', intnum)
                # print('last=',enc_str[59])
            out_str = out_str + enc_str[intnum]
        else:
            out_str = ''
        return out_str
    def num_to_sym_registered(intnum):
        # converts numbers to 3-symbols string
        # only registered users can create shortened links with 4 symbols like u9.by/aBcD others - only 5 symbols length
        # intnum=intnum+reserved
        out_str = ''
        if 0 <= intnum <= reserved:
            while intnum > len(enc_str) - 1:
                current = intnum % (len(enc_str) - 1)
                # print ('division=',current,enc_str[current])
                out_str = out_str + enc_str[current]
                intnum = math.floor(intnum / (len(enc_str) - 1))
                # print('rest=', intnum)
                # print('last=',enc_str[59])
            out_str = out_str + enc_str[intnum]
        else:
            out_str = ''
        return out_str
    def sym_to_num(str_num):
        # makes reversed operation - converts string to number
        intnum = 0
        str_num = str_num[::-1]
        # print(str_num)
        for i in range(len(str_num)):
            if enc_str.find(str_num[i]) >= 0:
                if i == 0:
                    rest = enc_str.find(str_num[i])
                if 0 < i < len(str_num):
                    rest = rest * 60 + enc_str.find(str_num[i])
                #  print('symbol no=',i,' is', str_num[i],' its position ',enc_str.find(str_num[i]),'  result is ',rest)
        return rest

class Leads(models.Model):
    urlentry = models.ForeignKey(Urlentry, on_delete=models.CASCADE)
    follow_date = models.DateTimeField('date when link was followed', auto_now=True)
    follower_info = models.TextField()
    follower_os_info = models.TextField()
    follower_fromwhere = models.TextField()
    def __str__(self):
        return self.follower_info

polls/forms.py
from django.forms import ModelForm
from django.forms.widgets import HiddenInput
from .models import Urlentry, Leads

# class DateToFromForm(ModelForm):
#     class Meta:
#         model = Urlentry
#         fields = ['datetime_available_from', 'datetime_available_to']

class UrlentryForm(ModelForm):
    class Meta:
        model = Urlentry
        fields = ['url_text', 'author', 'url_id', 'datetime_available_from', 'datetime_available_to', 'partner_ads','qr_code','snapshot']
    def __init__(self, *args, **kwargs):
        hide_condition = kwargs.pop('hide_condition', None)
        super(UrlentryForm, self).__init__(*args, **kwargs)
        if hide_condition:
            self.fields['author'].widget = HiddenInput()
            self.fields['url_id'].widget = HiddenInput()
            self.fields['url_id'].required = False
            self.fields['datetime_available_from'].widget = HiddenInput()
            self.fields['datetime_available_from'].required = False
            self.fields['datetime_available_to'].widget = HiddenInput()
            self.fields['datetime_available_to'].required = False
            self.fields['partner_ads'].widget = HiddenInput()
            self.fields['partner_ads'].required = False
            self.fields['qr_code'].widget = HiddenInput()
            self.fields['qr_code'].required = False
            self.fields['snapshot'].widget = HiddenInput()
            self.fields['snapshot'].required = False
            # or alternately:  del self.fields['fieldname']  to remove it from the form altogether.

class UrlentryFormShort(ModelForm):
    class Meta:
        model = Urlentry
        fields = ['url_text', 'partner_ads']
    def __init__(self, *args, **kwargs):
        super(UrlentryFormShort, self).__init__(*args, **kwargs)
        self.fields['url_text'].widget = HiddenInput()
        self.fields['partner_ads'].widget = HiddenInput()
        #self.fields['datetime_available_from'].required = False
        #self.fields['datetime_available_to'].required = False

class LeadsForm(ModelForm):
    class Meta:
        model = Leads
        fields = ['follower_info']

authentication/views.py
from django.shortcuts import render, redirect
from .forms import CreateUserForm, CheckCustomerForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .decorators import unauthenticated_user, allowed_users, staff_only
from django.contrib.auth.models import User, Group
from django.views import generic
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group, User
from .models import Profile, Custcode
import json
import os

#import secrets from secrets.json file
def get_secret(setting):
    with open('secrets.json') as secrets_file:
        secrets = json.load(secrets_file)
    """Get secret setting or fail with ImproperlyConfigured"""
    try:
        return secrets[setting]
    except:
        pass


@login_required(login_url='auth:login')
# @allowed_users(allowed_roles=['customer', 'admin'])
def profile_page(request, pk):  #shows profile details
    profile = Profile.objects.get(pk=pk)
    group = Group.objects.filter(id=profile.user.id).all()
    groupstring = 'User'
    if profile.user.is_staff:
        groupstring = 'Customer'
    return render(request, 'authentication/profile.html', context={
        'profile': Profile.objects.get(pk=pk),
        'group':group,
        'groupstring':groupstring,
    })

decorators = [login_required(login_url='auth:login'), staff_only]
@method_decorator(staff_only, name='dispatch')
class UsersView(generic.ListView):  #this page is available only to admin and serves to see all users and manipulate their rights
    template_name = 'authentication/users.html'
    context_object_name = 'user_list'
    def get_queryset(self):
        return Profile.objects.all()

@login_required(login_url='auth:login')
def customers_page(request, pk): #this page is for granting access to is_staff variable
    groupstring = 'user'
    profile = Profile.objects.get(pk=pk)
    user = profile.user
    if request.method == "POST":
        if not request.user.is_superuser:
            form = CheckCustomerForm(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                if cd['codeword']==get_secret('SECRET_KEY'):
                    if user.is_staff==False:
                        user.is_staff=True
                    user.save()
                #Profile.objects.create(user=user).save()
                    messages.success(request, 'User was successfully addedd to Customers group')
                else:
                    messages.error(request, 'Incorrect codeword, please try again')
        else:
            profile.user.is_staff = not user.is_staff
            profile.user.save()
    else:
        if request.user.is_superuser:
            user = User.objects.get(pk=pk)
            user.is_staff = not user.is_staff
            groupstring = 'user'
            user.save()
        form = CheckCustomerForm()
        if form.is_valid():
            form.save()
    group = user.groups.all()  ### other places
    for grp in group:
        if str(grp).find('customer')>=0:
            groupstring = 'customer'
        else:
            groupstring = 'user'
    return render(request, 'authentication/customer.html', context={
        'profile': Profile.objects.get(pk=pk), 'group': group, 'method': request.method,
        'form': form,
        })


@unauthenticated_user
def register_page(request):
    # if not Group.objects.filter(name='customer').exists():
    #     Group.objects.create(name='customer')
    #     Group.objects.create(name='admin')
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            messages.success(request, 'Account was created for ' + form.cleaned_data.get('username'))
            return redirect('auth:login')
        else:
            messages.error(request, 'Got a registration error: ' + str(form.error_messages))
    else:
        form = CreateUserForm()
    context = {'form': form}
    return render(request, 'authentication/reg.html', context)

@unauthenticated_user
def login_page(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('polls:index')
        else:
            messages.warning(request, 'Username or Password is incorrect')
    return render(request, 'authentication/login.html')

def logout_page(request):
    logout(request)
    return redirect('auth:login')

polls/templates/polls/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block Title %}Links{% endblock %}</title>
    <style type="text/css">

    </style>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" />
    
    <style type="text/css">
  BODY {
  background: "https://u9.by/uby/bg.jpg"; /* Фоновый рисунок */
  }
  
  </style>

</head>
<body>
    {% include 'polls/nav.html' %}
    <div class="container">
        {% block Body %}{% endblock %}
    </div>

    <script src="{% static 'js/bootstrap.bundle.js' %}" type="text/javascript"></script>

    <script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <!-- Optional theme --> <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
    

website4 polls.u9.by
</body>
</html>

polls/templates/polls/clicks.html
{% with total=urlentry.leads_set.all.count %}
{{ total }}
{% endwith %}

polls/templates/polls/detail.html
{% extends 'polls/base.html' %}
{% block Title %}{{ urlentry.url_short }} Detail{% endblock %}
{% block Body %}
<script src="https://cdn.rawgit.com/davidshimjs/qrcodejs/gh-pages/qrcode.min.js"></script>
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
<!-- jQuery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

  <!-- XDSoft DateTimePicker -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>

    
<h1><a href="https://u9.by/{{ urlentry.url_short }}">
            u9.by/{{ urlentry.url_short }}
                       </a>
        </h1>
<div id="qrcode"></div>
<script type="text/javascript">
var qrcode = new QRCode(document.getElementById("qrcode"), {
	text: "u9.by/{{ urlentry.url_short }}",
	width: 100,
	height: 100,
	colorDark : "#5868bf",
	colorLight : "#ffffff",
	correctLevel : QRCode.CorrectLevel.L
});
</script>
<br>
{% if urlentry.author == request.user %}
<button type="button" onclick="location.href='{% url 'polls:results' urlentry.id %}'" class="btn btn-danger">
See statistics of following this link
   </button>
{% endif %}

            {% if form.errors %}
                <p style="color: orangered">Got errors! {{ form.errors }}</p>
            {% endif %}
            {% for message in messages %}
                <p style="color: turquoise">{{ message }}</p>
            {% endfor %}

    <form action="{% url 'polls:update' urlentry.id %}" method="post">
        {% csrf_token %}
        <br>
        <fieldset>
            <legend><h2>Link content</h2></legend>
            <label><strong>Author: </strong>{{ urlentry.author }}</label> <br>
            <label><strong>Create date: </strong>{{ urlentry.create_date }}</label> <br>
            <label><strong>URL: </strong>
                {% if urlentry.author == request.user %}
                <input type="text" name="url_text" id="url_text" value="{{ urlentry.url_text }}">
                {% endif %}
                <a href="{{ urlentry.url_text }}">Go original Link!</a></label>
            <br>
             <label><strong>QR code to original link: </strong> <a href={{ urlentry.qr_code }}>generate</a></label> <br>
            <img src="{{ urlentry.qr_code }}" width="100" height="100" alt="qr"><br>
            {% if urlentry.author == request.user %}
                {% if request.user.is_staff %}
                       <br>
                        <legend><h2>Customer section</h2></legend>
                        <label><strong>Snapshot: </strong> <a href={{ urlentry.snapshot }}>take</a></label> <br>
                        <img src="{{ urlentry.snapshot }}" width="204" height="152" alt="snapshot"><br>
                        <label><strong>Partner ads: </strong>
                            <input type="text" name="partner_ads" id="partner_ads" value="{{ urlentry.partner_ads }}">
                        </label>
                        <br>
                        <label><strong>Link available </strong>
                            <div class="container">
   <div class='col-md-5'>
      <div class="form-group">
          from:
         <div class='input-group' id='datetimepicker06'>
            <input id="datetimepicker6" type='datetime-local' class="form-control" name="datetime_available_from" id="datetime_available_from" value="{{ urlentry.datetime_available_from|date:'dd.mm.YYYYTHH:ii' }}" />

         </div>
      </div>
   </div>
   <div class='col-md-5'>
      <div class="form-group">
          to:
         <div class='input-group' id='datetimepicker7'>
            <input type='datetime-local' class="form-control" name="datetime_available_to" id="datetime_available_to" value="{{ urlentry.datetime_available_to }}"/>
            
         </div>
      </div>
   </div>
</div>
<script type="text/javascript">
   $(document).ready(function () {
       $('#datetimepicker6').datetimepicker({
                 defaultDate: "{{ urlentry.datetime_available_from }}"
             });
       $('#datetimepicker7').datetimepicker({
   useCurrent: false //Important! See issue #1075
   });
       $("#datetimepicker6").on("dp.change", function (e) {
           $('#datetimepicker7').data("DateTimePicker").minDate(e.date);
       });
       $("#datetimepicker7").on("dp.change", function (e) {
           $('#datetimepicker6').data("DateTimePicker").maxDate(e.date);
       });
   });
</script>
                    </fieldset>
                {% endif %}  {% endif %}
        {% if urlentry.author == request.user and request.user.is_staff %}
        <br><input type="submit" class="btn btn-danger" value="Update Link">
        {% endif %}
        {% if urlentry.author == request.user %}
                        <br> <br>
        <legend><h2>Widgets</h2></legend>
<!-- Bootstrap 5 -->
<div class="accordion" id="menu">
  <!-- item-1 -->
  <div class="accordion-item">
    <h2 class="accordion-header">
  <button class="accordion-button collapsed bg-warning text-dark" type="button" data-bs-toggle="collapse" data-bs-target="#item-1">
     <h4>Clicks counter</h4>
      </button>
    </h2>
    <!-- класс show делает пункт открытым -->
    <div id="item-1" class="accordion-collapse collapse" data-bs-parent="#menu">
      <div class="accordion-body">
         <b> Direct link: </b> <a href="https://preclass.u9.by/polls/{{ urlentry.pk }}/results/get">https://preclass.u9.by/polls/{{ urlentry.pk }}/results/get</a>
       <br><b> PHP: </b> <br>
          &lt;?php echo file_get_contents(&quot;https://preclass.u9.by/polls/{{ urlentry.pk }}/results/get&quot;); ?&gt;
          <br><b> JavaScript: </b>
           <br>
&lt;div id=&quot;raz1&quot;&gt;&lt;/div&gt;
&lt;script&gt;
(function(){
  var http = new XMLHttpRequest();
  http.open('GET', 'https://preclass.u9.by/polls/{{ urlentry.pk }}/results/get');
  http.onreadystatechange = function () {
    if (this.readyState == 4 &amp;&amp; this.status == 200) {
      document.getElementById('raz1').innerHTML = this.responseText;
    }
  }
  http.send(null);
})()
&lt;/script&gt;
        <br> <br>
      </div>
    </div>
  </div>
      {% endif %}
{% if urlentry.author == request.user and request.user.is_staff %}
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed bg-warning text-dark" type="button" data-bs-toggle="collapse" data-bs-target="#item-2">
       <h4>Short link with snapshot</h4>
      </button>
    </h2>
    <div id="item-2" class="accordion-collapse collapse" data-bs-parent="#menu">
      <div class="accordion-body">
          <b> HTML code: </b> <br>
          &lt;a href="https://preclass.u9.by/{{ urlentry.url_short }}">&lt;img src="{{ urlentry.snapshot }}" width="204" height="152" alt="snapshot">&lt;/a>
         <br> <br><b> Result: </b> <br>
        <a href="https://preclass.u9.by/{{ urlentry.url_short }}">
               <img src="{{ urlentry.snapshot }}" width="204" height="152" alt="snapshot">
        </a>
      </div>
    </div>
  </div>
{% endif %}
</div>


    </form>
<br>
<br>
...
{% endblock %}

polls/templates/polls/index.html
{% extends 'polls/base.html' %}
{% block Title %}Links List{% endblock %}
{% block Body %}

<style>
   .colortext {
     color: red; /* Красный цвет выделения */
   }
  </style>

{% if links_list %}
  
      {% if request.user.is_superuser %}
<legend>Links of all authors:</legend>

    {% for links in links_list %}
       
        <a href="{% url 'polls:detail' links.id %}">
          {{ links.url_text|slice:':75' }}
        </a><br> 
           <b>author:</b>[{{ links.author }}] {% if links.author.is_staff %} <span class="colortext">(customer)</span> {% endif%}
            <b>date:</b>[{{ links.create_date }}]
        <a href="{% url 'polls:delete' links.id %}" type="button" class="btn btn-danger btn-sm">
                  Delete
        </a><br> <br> 
            {% endfor %}
      <br><legend>Your links, [{{ request.user.username }}]</legend>
        {% endif %}

        {% if links.author == request.user %}
        <legend>Your links as an author:</legend>
      {% endif %}
       {% for links in links_list %}
      {% if links.author == request.user %}

        <a href="{% url 'polls:detail' links.id %}">
          {{ links.url_text|slice:':75' }}
        </a>
           <b>date:</b>[{{ links.create_date }}]
        <a href="{% url 'polls:delete' links.id %}" type="button" class="btn btn-danger btn-sm">
                  Delete
        </a> <br>
        {% endif %}
      {% endfor %}



{% else %}
  <p>No links avaliable.</p>
{% endif %}
    {% if request.user.is_authenticated %}
        <a href="{% url 'polls:new' %}"  type="button" class="btn btn-danger">Add New Link</a>
    {% endif %}
   {% if not request.user.is_authenticated %} 
  <span class="colortext"> <b>Please login or register to shorten links </b></span>  <br>  <br> 
  <b>  Advantages </b> <br>
- Short link format <b>u9.by/aBc7D</b><br> 
- From 4 to 5 characters in a shortened link after / <br> 
- The shortened link uses only human-readable characters (a-z, A-Z, and the numbers 2 to 9)<br> 
- 0 and 1 are not used, so as not to confuse them with Latin O and I<br> 
- When you click on a shortened link, statistics are collected that are visible in your personal account<br> 
- QR code generator<br> 
- Embeddable link click count (in PHP and JavaScript)<br> 
<br> 
<b>Advanced users (by subscription*)</b><br> 
- Short link format <b>u9.by/aB7</b> up to 3 characters<br> 
- Browser and OS Information<br> 
- What site or account did the user come from<br> 
- Embeddable screenshot of the site that the user goes to via the link<br> 
- Setting the date and time of the beginning / end of the availability of the link <br> 
- The ability to link ads to click on the link<br>
<i>*subscription can be paid for a short number via SMS, <br> the cost is approximately two cups of coffee.<br>  One payment - registration forever.</i><br> <br> 
<b>Future plans (by subscription*)</b><br> 
- The ability to indicate human-readable words <b>u9.by/Firma</b><br> 
- Customize the look of the page on which the image is displayed, add advertising.<br> 
- Adjust its frequency (for example, every third click will cause ads to be displayed on the affiliate link you have built in)<br> 
- Embeddable countdown counter before the start / until the end of the availability of the link<br> 
- Extended statistics in a personal account, the set of which is constantly updated, namely, brief country click-through statistics<br> 
    {% endif %}
{% endblock %}

polls/templates/polls/nav.html
<nav class="navbar navbar-expand-md navbar-light" style="background-color: #34ebd2;">
   <div class="container container-fluid">
      <img src="https://u9.by/uby/U9logob.png" width="222" height="80"></img>
    <a class="navbar-brand" href="#"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
           {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'polls:index' %}" aria-current="page"><b>List</b></a>
        </li>
       
            <li class="nav-item">
                <a class="nav-link" href="{% url 'polls:new' %}"><b>New Link</b></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auth:profile' request.user.profile.id %}">Profile [{{ user.username }}]</a>
            </li>
          {% if request.user.is_superuser %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auth:users' %}">Users</a>
            </li>
        {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auth:logout' %}">Logout</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auth:login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auth:reg' %}">Register</a>
            </li>
        {% endif %}
      </ul>
    </div>
  </div>
  <div class="container">
      <input type="button" class="btn btn-info" onclick="location.href='https://a.u9.by'" value="Freeware soft & music">
      </div>
</nav>

polls/templates/polls/results.html
{% extends 'polls/base.html' %}
{% block Title %}{{ urlentry.url_short }} Statistics{% endblock %}
{% block Body %}

    <h1><a href="https://preclass.u9.by/{{ urlentry.url_short }}">
            https://preclass.u9.by/{{ urlentry.url_short }}
                       </a>
        </h1>
    {% if urlentry.leads_set.all %}
    <legend>
{% with total=urlentry.leads_set.all.count %}
    {{ total }} click{{ total|pluralize }}
{% endwith %}
    </legend>
<br>  {{ leads_list }}
<br>  {{ count }}


    {% endif %}
<ul>
    {% for leads in urlentry.leads_set.all %}
        <li>
            <b>datetime:</b>{{ leads.follow_date }}
            <b>  from website:</b>{{ leads.follower_info }}
            <b>  IP:</b> {{ leads.follower_fromwhere }} <br>
            <b>user device config:</b> {{ leads.follower_os_info }}{{ leads.follower_os_info|pluralize }}
        </li>
    {% endfor %}
    {% if not urlentry.leads_set.all %}
    <b>no clicks on the link </b>
    {% endif %}
    <br>

</ul>

<a href="{% url 'polls:index' %}">Back to Links</a>
 <br>
...
{% endblock %}